### ISSUE TITLE
When "Borrowing" Equipment for Contracts not all Items are being Spawned

### ISSUE THREAD

**Issue by cwattyeso** [Mmtrx/FS22_BetterContracts#20] opened 2022-07-28 15:20 UTC
Have updated to the latest version of the Mod and have experienced the same issue now across three different maps and saves. When taking some contracts and Borrowing the equipment shown for the contract, not all the equipment shown actually gets spawned into the map at the store for use. One such example is Sugar Beet Harvesting contracts. They show the Grimme Rexor Harvester, Two JCB Fastrac Tractors and Two Fliegl Trailers. If you borrow the equipment, when you go to the store to collect it only the Harvester and two tractors are there. No Trailers can be found anywhere so it's impossible to transport the crop for the contract, unless you revsert to using your own equipment if you have any or having to manual lease trailers via the store.

**Comment by Yiddan** [comment] 2022-07-29 08:26
That's right, i always forget to report the problem (even if im not totally sure this issue is caused by better contracts mod)
Another example is on cotton contracts, the leased trailer is actually a (crosetto i think) grain trailer, so unusable to pickup bales.

**Comment by Mmtrx** [comment] 2022-07-29 19:17
Hm,
@cwattyeso are you sure about the Fliegl trailers? My extension to mission vehicles specifies a combination of 1x Rexor / 2x Fastrac8330 / 2x RudolphSohn tdk301RA trailers for a large field sugarbeet mission.
Can you reproduce the situation, and then show me the log.txt?

@Yiddan, I checked the missionVehicles.xml from base game, they only specify Lizard Module4/ ModuleX or mcCormack cottonTagTrailer for cotton missions. My extension to missionVehicles has nothing for cotton. So there maybe something else going on. Could you also provide a log file for further analysis?

**Comment by Yiddan** [comment] 2022-07-29 22:16
Thanks for checking what i said. I was really not sure those 2 (opener and me) "issues" are related to better contracts. But i dont know what other mod i use could modify missions vehicle...
The map i currently play and had those problems is clamsden farm.
So tomorrow ill drop an eye in map's files and see if its not the culprit
And will ultimately provide a log if it can help 😉

**Comment by cwattyeso** [comment] 2022-07-29 23:27
I'm playing Calmsden Farm in Single Player and Multiplayer and having the issue with Trailers not appearing when borrowing Harvest Equipment. I also have it in Single Player on the Riverview Map, Elm Creek Map by Giants and the new Elm Creek 4x Map by Stevie.

I checked tonight on my Riverview save and when the Sugar Beet Harvest Contracts offer a Ropa Harvester that's when they offer the Fliegl Trailer, so I assumed it was meant to be the same trailers with the Grimme Rexor harvester. You are probably correct and it should be Rudolph trailers, but regardless of what they should be they never ever get spawned in when you choose the borrow equipment option.

I'll try and grab a log file the next time I see that set of equipment offered for a job. Unfortunately I've just finished all the Sugar Beet contracts across all my saves in what has been probably the longest and most monotonous week of my Farm Sim life lol

**Comment by Mmtrx** [comment] 2022-08-01 19:40
When I made the game use my specified set of additional mission vehicles for a sugarbeet harvest on a large field, I  got some log errors about loading the 2 Rudolph trailers. But they did load and showed up at the store. So I fixed their configs in the `/missionVehicles/baseGame.xml` (inside my mod). You can download the fix [here](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.3.2b).

Also, if you can zip your Elmcreek savegame folder and upload it here, I will try to test it within your setup.

**Comment by Yiddan** [comment] 2022-08-02 09:50
Thanks Mmtrx ;)
Couldnt play enough recently to have one of those issues again. But i will test the last test release ;)

**Comment by Mmtrx** [comment] 2022-08-19 07:30
Nothing heard. So I will close this now. If this error happens again, you could re-open the issue.

**Closed by Mmtrx** 2022-08-19 07:30 UTC
