### ISSUE TITLE
Combination mistake

### ISSUE THREAD

**Issue by Inoque71** [Mmtrx/FS22_BetterContracts#24] opened 2022-08-15 19:43 UTC
I raise this only because some players they don't know how to change.
File - basegame.xml
Line - 293
Mission - Sow / Small
Tractor Massey Ferguson Series 3700AL don't have front 3-Point. This 'group' come with weight 650kg.
Line - 394
Mission - Weed / Small
Tractor Massey Ferguson Series 3700AL don't have front 3-Point. This 'group' come with weight 650kg.
Regards 
![fsScreen_2022_08_15_20_44_29](https://user-images.githubusercontent.com/73787877/184705899-075fa3fc-6745-4925-a102-1649a299b229.jpeg)

**Comment by Inoque71** [comment] 2022-08-16 19:58
Let's help this community (Modders) they are already past your free time to bring awesome mods to the player.
This my suggestion.

Line 292 (The Amazon 3000 Super requires 165hp and weight of 1000kg)


        <group fieldSize="small" variant="GRAIN">
            <vehicle filename="$data/vehicles/newHolland/t6/t6.xml">
                
                <configuration name="motor" id="3" />
                <configuration name="wheel" id="20" />
                <configuration name="fillUnit" id="1" />
            </vehicle>
            <vehicle filename="$data/vehicles/amazone/centaya3000Super/centaya3000Super.xml">
                
            </vehicle>
            <vehicle filename="$data/vehicles/tenwinkel/weight1000/weight1000.xml">
                <configuration name="baseMaterial" id="7" />
            </vehicle>
        </group>

Line 392 (This tractor have 3-Point)

    <mission type="weed">
        <group fieldSize="small" rewardScale="0.7">
            <vehicle filename="$data/vehicles/zetor/majorCL80/majorCL80.xml">
                
                <configuration name="wheel" id="7" />
            </vehicle>
            <vehicle filename="$data/vehicles/einboeck/pneumaticstar900/pneumaticstar900.xml" /> 
            <vehicle filename="$data/vehicles/agco/weight650/weight650.xml">
                <configuration name="baseMaterial" id="7" />
            </vehicle>
        </group>

Regards

**Comment by Mmtrx** [comment] 2022-08-17 07:53
Hi @Inoque71 - thanks a lot!
Since you found this little error, I assume you also checked all the other mission vehicle combos. Really a lot of work, I appreciate it.
I just put your corrections in my local version and will push it to main branch here soon, so that it will get into the next release.

**Comment by Mmtrx** [comment] 2022-08-17 15:45
Fixed in latest [Relese](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.0)

**Comment by Inoque71** [comment] 2022-08-17 21:49
I will review on last release.
Question: some mission have this < rewardScale >. I done a few tests with and with out, I didn't notice any difference on reward for the contractor. If this is for the intention to increase the value of the contract I did it another way, add some code on betterContracts.lua. This code I found Giants Forum, some values were unrealistic and I adjust something more acceptable and add WeedMission.REWARD_PER_HA=XXXX.

**Comment by Mmtrx** [comment] 2022-08-18 08:31
Hey, you are right!
I think the <rewardScale> parm in the missionVehicles. xml was intended to compensate for possibly over- (or under-)sized equipment. I.e. if you specified a 12m weeder for a weeding job on a small field, you could set rewardScale to 0.7. Or set it to 1.5 for a tedious plowing job with a 3m plow on a 2ha field. The code to read in the <rewardScale> parm is contained in the original game source code.

**BUT** (I just checked): They never use it when calculating the total reward for a mission with leased equipment!

Your solution `WeedMission.REWARD_PER_HA=XXXX` is absolutely correct.

And thanks again for your tractor correction for the small grain sowing mission. In case you wondered: I removed the
`<configuration name="fillUnit" id="1" />` from 
`<vehicle filename="$data/vehicles/newHolland/t6/t6.xml">`,
because it's the default.

**Closed by Mmtrx** 2022-08-18 08:31 UTC
